This is for testing the developed models on real images and comparing the outputs and the time taken by them with current undustry standard approaches.

In [ ]:
# Importing the libraries
import numpy as np
import cv2
import tensorflow as tf
import pandas as pd
from tensorflow.keras.models import load_model

In [3]:
# Applying the predictions to form the edge image

# Defining the edges
matrices3x3 = {
    'mat_3x3_00': [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]
    ],
    'mat_3x3_01': [
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]
    ],
    'mat_3x3_11': [
        [0, 0, 0],
        [0, 0, 0],
        [255, 255, 255]
    ],
    'mat_3x3_12': [
        [255, 255, 255],
        [0, 0, 0],
        [0, 0, 0]
    ],
    'mat_3x3_13': [
        [255, 255, 255],
        [255, 255, 255],
        [0, 0, 0]
    ],
    'mat_3x3_14': [
        [0, 0, 0],
        [255, 255, 255],
        [255, 255, 255]
    ],
    'mat_3x3_21': [
        [255, 255, 0],
        [255, 0, 0],
        [0, 0, 0]
    ],
    'mat_3x3_22': [
        [0, 0, 255],
        [0, 255, 255],
        [255, 255, 255]
    ],
    'mat_3x3_23': [
        [255, 255, 0],
        [255, 0, 0],
        [0, 0, 0]
    ],
    'mat_3x3_24': [
        [0, 0, 255],
        [0, 255, 255],
        [255, 255, 255]
    ],
    'mat_3x3_31': [
        [255, 0, 0],
        [255, 0, 0],
        [255, 0, 0]
    ],
    'mat_3x3_32': [
        [0, 0, 255],
        [0, 0, 255],
        [0, 0, 255]
    ],
    'mat_3x3_33': [
        [0, 255, 255],
        [0, 255, 255],
        [0, 255, 255]
    ],
    'mat_3x3_34': [
        [255, 255, 0],
        [255, 255, 0],
        [255, 255, 0]
    ],
    'mat_3x3_41': [
        [255, 0, 0],
        [255, 255, 0],
        [255, 255, 255]
    ],
    'mat_3x3_42': [
        [0, 255, 255],
        [0, 0, 255],
        [0, 0, 0]
    ],
    'mat_3x3_43': [
        [255, 255, 255],
        [0, 255, 255],
        [0, 0, 255]
    ],
    'mat_3x3_44': [
        [0, 0, 0],
        [255, 0, 0],
        [255, 255, 0]
    ]
}

matrices5x5 = {
    'mat_5x5_00': [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],
    'mat_5x5_01': [
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]
    ],
    'mat_5x5_11': [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]
    ],
    'mat_5x5_12': [
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],
    'mat_5x5_13': [
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],
    'mat_5x5_14': [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]
    ],
    'mat_5x5_21': [
        [0, 0, 0, 0, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]
    ],
    'mat_5x5_22': [
        [255, 255, 255, 255, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],
    'mat_5x5_23': [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 255, 255, 255, 255]
    ],
    'mat_5x5_24': [
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 0, 0, 0, 0]
    ],
    'mat_5x5_31': [
        [0, 0, 0, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 255, 255]
    ],
    'mat_5x5_32': [
        [255, 255, 255, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 0, 0]
    ],
    'mat_5x5_33': [
        [0, 0, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 255, 255, 255]
    ],
    'mat_5x5_34': [
        [255, 255, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 0, 0, 0]
    ],
    'mat_5x5_41': [
        [255, 0, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 255, 0],
        [255, 255, 255, 255, 255]
    ],
    'mat_5x5_42': [
        [0, 255, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 0, 255],
        [0, 0, 0, 0, 0]
    ],
    'mat_5x5_43': [
        [0, 0, 0, 0, 0],
        [255, 0, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 255, 0]
    ],
    'mat_5x5_44': [
        [255, 255, 255, 255, 255],
        [0, 255, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 0, 255]
    ]
}

matrices7x7 = {
    'mat_7x7_00': [
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]
    ],
    'mat_7x7_01': [
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255]
    ],
    'mat_7x7_11': [
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255]
    ],
    'mat_7x7_12': [
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]
    ],
    'mat_7x7_13': [
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]
    ],
    'mat_7x7_14': [
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255]
    ],
    'mat_7x7_21': [
        [0, 0, 0, 0, 0, 0, 255],
        [0, 0, 0, 0, 0, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 255, 255, 255, 255, 255],
        [0, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255]
    ],
    'mat_7x7_22': [
        [255, 255, 255, 255, 255, 255, 0],
        [255, 255, 255, 255, 255, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 0, 0, 0, 0, 0],
        [255, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]
    ],
    'mat_7x7_23': [
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 255],
        [0, 0, 0, 0, 0, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 255, 255, 255, 255, 255],
        [0, 255, 255, 255, 255, 255, 255]
    ],
    'mat_7x7_24': [
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 0],
        [255, 255, 255, 255, 255, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 0, 0, 0, 0, 0],
        [255, 0, 0, 0, 0, 0, 0]
    ],
    'mat_7x7_31': [
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255]
    ],
    'mat_7x7_32': [
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0]
    ],
    'mat_7x7_33': [
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255]
    ],
    'mat_7x7_34': [
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0]
    ],
    'mat_7x7_41': [
        [255, 0, 0, 0, 0, 0, 0],
        [255, 255, 0, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 255, 0, 0],
        [255, 255, 255, 255, 255, 255, 0],
        [255, 255, 255, 255, 255, 255, 255]
    ],

    'mat_7x7_42': [
        [0, 255, 255, 255, 255, 255, 255],
        [0, 0, 255, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 0, 255, 255],
        [0, 0, 0, 0, 0, 0, 255],
        [0, 0, 0, 0, 0, 0, 0]
    ],

    'mat_7x7_43': [
        [0, 0, 0, 0, 0, 0, 0],
        [255, 0, 0, 0, 0, 0, 0],
        [255, 255, 0, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 255, 0, 0],
        [255, 255, 255, 255, 255, 255, 0]
    ],

    'mat_7x7_44': [
        [255, 255, 255, 255, 255, 255, 255],
        [0, 255, 255, 255, 255, 255, 255],
        [0, 0, 255, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 0, 255, 255],
        [0, 0, 0, 0, 0, 0, 255]
    ]
}


In [6]:
#pre-processing the images

def pre_process_image(image_path, compression_factor=2):
    # Read the image
    image = cv2.imread(image_path)

    # Convert to grayscale
    grayscale_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Access the grayscale image as a matrix
    grayscale_matrix = np.array(grayscale_image)

    
    # Compress the image by resizing
    original_height, original_width = grayscale_image.shape
    new_height = original_height // compression_factor
    new_width = original_width // compression_factor

    compressed_image = cv2.resize(grayscale_image, (new_width, new_height), interpolation=cv2.INTER_AREA)
    compressed_matrix = np.array(compressed_image)

    grayscale_matrix = grayscale_matrix / 255.0
    compressed_matrix = compressed_matrix / 255.0
    return grayscale_matrix, compressed_matrix

def display_image(image_matrix, title="Image"):
    cv2.imshow(title, image_matrix)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    
def save_image(image_matrix, file_name):
    cv2.imwrite(file_name, image_matrix)
    print(f"Image saved as '{file_name}'")


In [7]:
image_path = "/Ankit/Programs/RP/flower.jpg"
compression_factor = 4
image = cv2.imread(image_path)

grayscale_matrix, compressed_matrix = pre_process_image(image_path, compression_factor)

print("Grayscale Matrix:")
print(grayscale_matrix)

print("\nCompressed Matrix:")
print(compressed_matrix)

# Save the images
save_image(grayscale_matrix, "grayscale_image.jpg")
save_image(compressed_matrix, "compressed_image.jpg")

# Display the images
display_image(grayscale_matrix, title="Grayscale Image")
display_image(compressed_matrix, title="Compressed Image")

Grayscale Matrix:
[[0.26666667 0.28627451 0.30588235 ... 0.39607843 0.40784314 0.43137255]
 [0.25882353 0.27843137 0.29411765 ... 0.4        0.41176471 0.42745098]
 [0.26666667 0.27843137 0.29411765 ... 0.40784314 0.41568627 0.42745098]
 ...
 [0.03529412 0.03529412 0.05490196 ... 0.26666667 0.27058824 0.27843137]
 [0.03137255 0.03137255 0.05098039 ... 0.26666667 0.26666667 0.27843137]
 [0.03137255 0.02745098 0.05098039 ... 0.26666667 0.26666667 0.27843137]]

Compressed Matrix:
[[0.29019608 0.3254902  0.34509804 ... 0.36470588 0.39215686 0.41176471]
 [0.36078431 0.41176471 0.41568627 ... 0.35294118 0.40392157 0.41568627]
 [0.40784314 0.43921569 0.43137255 ... 0.2745098  0.37254902 0.4       ]
 ...
 [0.0627451  0.07843137 0.14117647 ... 0.29803922 0.29803922 0.30588235]
 [0.05882353 0.06666667 0.20392157 ... 0.28235294 0.27843137 0.28627451]
 [0.05098039 0.08627451 0.29803922 ... 0.2745098  0.2627451  0.27058824]]
Image saved as 'grayscale_image.jpg'
Image saved as 'compressed_image.jpg'

In [8]:
print(f"Size of original matrix = {grayscale_matrix.shape} ") 
print(f"Size of compressed matrix = {compressed_matrix.shape} ") 

Size of original matrix = (320, 320) 
Size of compressed matrix = (80, 80) 


In [13]:
# Loading the model and predicting from image
def load_nn_model(model_path):
    model = load_model(model_path)
    return model

def predict_from_image(model, image_matrix, window_size=5): # Uses sliding window to process the entire image in batches
    height, width = image_matrix.shape
    predictions = []
    row_limit = height
    col_limit = width
    print(f"Making predictions for {row_limit} rows and {col_limit} columns")
    # Slide the window across the image
    for i in range(0, row_limit, window_size):
        print(f"Predicting for {i}/{row_limit}")
        for j in range(0, col_limit, window_size):
            # Extract the patch
            patch = image_matrix[i:i + window_size, j:j + window_size]
            # Preprocess the patch (flatten and reshape for Conv1D model)
            patch = patch.flatten()
            # print(f"Predicting for {i}/{row_limit}, {j}/{col_limit}")
            patch = patch.reshape(1, -1, 1)
            # Make predictions
            pred = model.predict(patch)

            # Interpret predictions
            has_edge = "Yes" if pred[0][0] > 0.5 else "No"  # Binary output (threshold at 0.5)
            edge_no1 = np.argmax(pred[1], axis=1)[0]
            edge_no2 = np.argmax(pred[2], axis=1)[0]
            if has_edge == "Yes" and edge_no1 > 0 and edge_no2 > 0:
                if window_size == 3:
                    edge_matrix = matrices3x3[f'mat_3x3_{edge_no1}{edge_no2}']
                elif window_size == 5:
                    edge_matrix = matrices5x5[f'mat_5x5_{edge_no1}{edge_no2}']
                else:
                    edge_matrix = matrices7x7[f'mat_7x7_{edge_no1}{edge_no2}']
            else:
                edge_matrix = np.zeros((window_size, window_size))

            # Replace the corresponding part of the image matrix with the edge matrix
            image_matrix[i:i + window_size, j:j + window_size] = edge_matrix

            predictions.append((has_edge, edge_no1, edge_no2))
            

    return predictions, image_matrix

def make_edge_matrix(image_matrix, predictions, window_size):
    height, width = image_matrix.shape
    row_limit = height
    col_limit = width
    output_image = np.copy(image_matrix)
    x = 0
    for i in range(0, row_limit, window_size):
        for j in range(0, col_limit, window_size):
            
            has_edge, edge_no1, edge_no2 = predictions[x]
            x+=1
            if has_edge == "Yes" and edge_no1 > 0 and edge_no2 > 0:
                # Determine the matrix size based on the edge_no1
                if window_size == 3:
                    edge_matrix = matrices3x3[f'mat_3x3_{edge_no1}{edge_no2}']
                elif window_size == 5:
                    edge_matrix = matrices5x5[f'mat_5x5_{edge_no1}{edge_no2}']
                else:
                    edge_matrix = matrices7x7[f'mat_7x7_{edge_no1}{edge_no2}']
            else:
                edge_matrix = np.zeros((window_size, window_size))

            # Replace the corresponding part of the image matrix with the edge matrix
            output_image[i:i + window_size, j:j + window_size] = edge_matrix

    return output_image

def neural_newtork_edge_detection(image_path, model_path, output_path, compression_factor=2, window_size=5):
    
    model = load_model(model_path)
    print(f"Model loaded from {model_path}")
    grayscale_matrix, compressed_matrix = pre_process_image(image_path, compression_factor)
    print(f"Image pre-processed with compression factor {compression_factor}")
    print(f"Compressed image shape: {compressed_matrix.shape}")
    predictions, image_matrix = predict_from_image(model, compressed_matrix, window_size)
    print(f"Predictions made for {len(predictions)} patches")
    return predictions, image_matrix
    # # output_matrix = make_edge_matrix(compressed_matrix, predictions, window_size)
    # output_matrix = image_matrix
    # print(f"Edge matrices made for {len(predictions)} patches")
    # save_image(output_matrix, output_path)
    # print(f"Output image saved to {output_path}")
    # display_image(output_matrix, title="Output Image")




In [14]:
# Driver code
image_path = "/Ankit/Programs/RP/flower.jpg"
model_path = "/Ankit/Programs/RP/multi_output_model_25x25_smaller.keras"
output_path = "/Ankit/Programs/RP/output_flower.jpg"
compression_factor = 2
window_size = 5
predictions, image_matrix = neural_newtork_edge_detection(image_path, model_path, output_path, compression_factor, window_size)

Model loaded from /Ankit/Programs/RP/multi_output_model_25x25_smaller.keras
Image pre-processed with compression factor 2
Compressed image shape: (160, 160)
Making predictions for 160 rows and 160 columns
Predicting for 0/160
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
1/1 ━━━━━━━━━

In [16]:
print(predictions)

[('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('Yes', 0, 2), ('Yes', 0, 2), ('No', 0, 0), ('Yes', 0, 2), ('Yes', 0, 2), ('No', 0, 0), ('No', 0, 2), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 2), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('Yes', 0, 2), ('Yes', 0, 2), ('Yes', 0, 2), ('No', 0, 0), ('Yes', 0, 2), ('Yes', 0, 2), ('Yes', 0, 2), ('No', 0, 2), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 2), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('No', 0, 0), ('Yes', 0, 2), ('Yes', 0, 2), ('Yes', 0, 2), ('Yes', 0, 2), ('No'

In [47]:
print(compressed_matrix[5:5 + window_size, 5:5 + window_size])

[[ 74 117 122 117 116]
 [ 87 121 120 117 115]
 [ 87 118 120 119 117]
 [ 70 111 114 117 116]
 [ 51  95 111 118 116]]


In [15]:
display_image(image_matrix, title="Output Image")