In [1]:
matrices3x3 = {
    'mat_3x3_00': [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]
    ],
    'mat_3x3_01': [
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]
    ],
    'mat_3x3_11': [
        [0, 0, 0],
        [0, 0, 0],
        [255, 255, 255]
    ],
    'mat_3x3_12': [
        [255, 255, 255],
        [0, 0, 0],
        [0, 0, 0]
    ],
    'mat_3x3_13': [
        [255, 255, 255],
        [255, 255, 255],
        [0, 0, 0]
    ],
    'mat_3x3_14': [
        [0, 0, 0],
        [255, 255, 255],
        [255, 255, 255]
    ],
    'mat_3x3_21': [
        [255, 255, 0],
        [255, 0, 0],
        [0, 0, 0]
    ],
    'mat_3x3_22': [
        [0, 0, 255],
        [0, 255, 255],
        [255, 255, 255]
    ],
    'mat_3x3_23': [
        [0, 0, 0],
        [0, 0, 255],
        [0, 255, 255]
    ],
    'mat_3x3_24': [
        [255, 255, 255],
        [255, 255, 0],
        [255, 0, 0]
    ],
    'mat_3x3_31': [
        [255, 0, 0],
        [255, 0, 0],
        [255, 0, 0]
    ],
    'mat_3x3_32': [
        [0, 0, 255],
        [0, 0, 255],
        [0, 0, 255]
    ],
    'mat_3x3_33': [
        [0, 255, 255],
        [0, 255, 255],
        [0, 255, 255]
    ],
    'mat_3x3_34': [
        [255, 255, 0],
        [255, 255, 0],
        [255, 255, 0]
    ],
    'mat_3x3_41': [
        [255, 0,   0],
        [255, 255, 0],
        [255, 255, 255]
    ],
    'mat_3x3_42': [
        [0, 255, 255],
        [0, 0,   255],
        [0, 0,   0]
    ],
    'mat_3x3_43': [
        [255, 255, 255],
        [0, 255, 255],
        [0, 0, 255]
    ],
    'mat_3x3_44': [
        [0, 0, 0],
        [255, 0, 0],
        [255, 255, 0]
    ]
}
matrices5x5 = {
    'mat_5x5_00': [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],
    'mat_5x5_01': [
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]
    ],
    'mat_5x5_11': [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]
    ],
    'mat_5x5_12': [
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],
    'mat_5x5_13': [
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],
    'mat_5x5_14': [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]
    ],
    'mat_5x5_21': [
        [0, 0, 0, 0, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]
    ],
    'mat_5x5_22': [
        [255, 255, 255, 255, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],
    'mat_5x5_23': [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 255, 255, 255, 255]
    ],
    'mat_5x5_24': [
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 0, 0, 0, 0]
    ],
    'mat_5x5_31': [
        [0, 0, 0, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 255, 255]
    ],
    'mat_5x5_32': [
        [255, 255, 255, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 0, 0]
    ],
    'mat_5x5_33': [
        [0, 0, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 255, 255, 255]
    ],
    'mat_5x5_34': [
        [255, 255, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 0, 0, 0]
    ],
    'mat_5x5_41': [
        [255, 0, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 255, 0],
        [255, 255, 255, 255, 255]
    ],
    'mat_5x5_42': [
        [0, 255, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 0, 255],
        [0, 0, 0, 0, 0]
    ],
    'mat_5x5_43': [
        [0, 0, 0, 0, 0],
        [255, 0, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 255, 0]
    ],
    'mat_5x5_44': [
        [255, 255, 255, 255, 255],
        [0, 255, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 0, 255]
    ]
}
matrices7x7 = {
    'mat_7x7_00': [
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]
    ],
    'mat_7x7_01': [
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255]
    ],
    'mat_7x7_11': [
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255]
    ],
    'mat_7x7_12': [
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]
    ],
    'mat_7x7_13': [
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]
    ],
    'mat_7x7_14': [
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255]
    ],
    'mat_7x7_21': [
        [0, 0, 0, 0, 0, 0, 255],
        [0, 0, 0, 0, 0, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 255, 255, 255, 255, 255],
        [0, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255]
    ],
    'mat_7x7_22': [
        [255, 255, 255, 255, 255, 255, 0],
        [255, 255, 255, 255, 255, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 0, 0, 0, 0, 0],
        [255, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]
    ],
    'mat_7x7_23': [
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 255],
        [0, 0, 0, 0, 0, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 255, 255, 255, 255, 255],
        [0, 255, 255, 255, 255, 255, 255]
    ],
    'mat_7x7_24': [
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 0],
        [255, 255, 255, 255, 255, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 0, 0, 0, 0, 0],
        [255, 0, 0, 0, 0, 0, 0]
    ],
    'mat_7x7_31': [
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255]
    ],
    'mat_7x7_32': [
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0]
    ],
    'mat_7x7_33': [
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255]
    ],
    'mat_7x7_34': [
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0]
    ],
    'mat_7x7_41': [
        [255, 0, 0, 0, 0, 0, 0],
        [255, 255, 0, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 255, 0, 0],
        [255, 255, 255, 255, 255, 255, 0],
        [255, 255, 255, 255, 255, 255, 255]
    ],

    'mat_7x7_42': [
        [0, 255, 255, 255, 255, 255, 255],
        [0, 0, 255, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 0, 255, 255],
        [0, 0, 0, 0, 0, 0, 255],
        [0, 0, 0, 0, 0, 0, 0]
    ],

    'mat_7x7_43': [
        [0, 0, 0, 0, 0, 0, 0],
        [255, 0, 0, 0, 0, 0, 0],
        [255, 255, 0, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 255, 0, 0],
        [255, 255, 255, 255, 255, 255, 0]
    ],

    'mat_7x7_44': [
        [255, 255, 255, 255, 255, 255, 255],
        [0, 255, 255, 255, 255, 255, 255],
        [0, 0, 255, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 0, 255, 255],
        [0, 0, 0, 0, 0, 0, 255]
    ]
}


In [2]:
import numpy as np
import pandas as pd

# Function to add random noise to a matrix
def add_noise(matrix, mean=0, std_dev=30):
    gaussian_noise = np.random.normal(mean, std_dev, matrix.shape)
    noisy_matrix = matrix + gaussian_noise
    noisy_matrix = np.clip(noisy_matrix, 0, 255)  # Ensure values are within [0, 255]
    return noisy_matrix

#function to generate csv file for the matrices
def generate_csv(matrices, mean, std_dev, num_iterations, filename):
    data = []

    for matrix_name, matrix in matrices.items():
        base_matrix = np.array(matrix)
        first_digit = int(matrix_name[-2])
        second_digit = int(matrix_name[-1])
        size = len(matrix[0])

        for _ in range(num_iterations):
            # Add random noise
            noisy_matrix = add_noise(base_matrix, mean, std_dev)
            #normalise the matrix
            noisy_matrix = noisy_matrix/255.0
            # Flatten the matrix to store as a row
            noisy_matrix_flat = noisy_matrix.flatten()
    
            if first_digit == 0:
                edge_detected = 0
            else:
                edge_detected = 1
            
            # Append the flattened matrix and labels to the data list
            data.append(list(noisy_matrix_flat) + [edge_detected, first_digit, second_digit])
    
    # Convert the data to a DataFrame and save to CSV
    columns = [f'pixel_{i}' for i in range(size*size)] + ['edge_detected', 'first_digit', 'second_digit']
    df = pd.DataFrame(data, columns=columns)

    df.to_csv(filename, index=False)

    print("CSV file generated successfully.")

In [9]:
matrices = matrices3x3
mean = 0
std_dev = 60
num_iterations = 2000
filename = 'test_3x3.csv'
generate_csv(matrices, mean, std_dev, num_iterations, filename)

CSV file generated successfully.


In [3]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score
from tensorflow.keras.models import load_model

def test_models(data, model):
    # Split the dataset into features (X_test) and labels (y1_test, y2_test, y3_test)
    X_test = data.iloc[:, :-3].values  # Assuming the last 3 columns are labels
    y1_test = data.iloc[:, -3].values  # Binary labels for output1
    y2_test = data.iloc[:, -2].values  # Multiclass labels for output2
    y3_test = data.iloc[:, -1].values  # Multiclass labels for output3

    # Print shapes for verification
    print("Shapes of data:")
    print("X_test:", X_test.shape)
    print("y1_test:", y1_test.shape)
    print("y2_test:", y2_test.shape)
    print("y3_test:", y3_test.shape)

    # Evaluate the model
    results = model.evaluate(X_test, {'output1': y1_test, 'output2': y2_test, 'output3': y3_test}, verbose=1)
    print("Test Results:", results)

    # Generate predictions
    preds = model.predict(X_test)
    y1_pred = (preds[0] > 0.5).astype(int)  # Binary predictions for output1
    y2_pred = np.argmax(preds[1], axis=1)  # Multiclass predictions for output2
    y3_pred = np.argmax(preds[2], axis=1)  # Multiclass predictions for output3

    # Confusion matrices
    print("\nConfusion Matrix for Output 1:")
    print(confusion_matrix(y1_test, y1_pred))

    print("\nConfusion Matrix for Output 2:")
    print(confusion_matrix(y2_test, y2_pred))

    print("\nConfusion Matrix for Output 3:")
    print(confusion_matrix(y3_test, y3_pred))

    # Accuracy scores
    print("\nAccuracy for Output 1:", accuracy_score(y1_test, y1_pred))
    print("Accuracy for Output 2:", accuracy_score(y2_test, y2_pred))
    print("Accuracy for Output 3:", accuracy_score(y3_test, y3_pred))


In [9]:
matrices = matrices3x3
mean = 0
std_dev = 70
num_iterations = 2000
filename = 'test_3x3.csv'
generate_csv(matrices, mean, std_dev, num_iterations, filename)

data = pd.read_csv("test_3x3.csv") 
model = load_model("C:\Ankit\Programs\RP\models\ed_9x9.keras")
test_models(data, model)

CSV file generated successfully.
Shapes of data:
X_test: (36000, 9)
y1_test: (36000,)
y2_test: (36000,)
y3_test: (36000,)
1125/1125 [==============================] - 2s 1ms/step - loss: 0.3347 - output1_loss: 0.0081 - output2_loss: 0.1520 - output3_loss: 0.1182 - output1_accuracy: 0.9975 - output2_accuracy: 0.9542 - output3_accuracy: 0.9601
Test Results: [0.3347403407096863, 0.00809877272695303, 0.1520358920097351, 0.1182268038392067, 0.9975277781486511, 0.9542499780654907, 0.9600833058357239]
1125/1125 [==============================] - 2s 1ms/step

Confusion Matrix for Output 1:
[[ 3942    58]
 [   31 31969]]

Confusion Matrix for Output 2:
[[3879    9   44   67    1]
 [  22 7692  201   19   66]
 [  88   98 7717   97    0]
 [  93    1  111 7682  113]
 [   3  215    1  398 7383]]

Confusion Matrix for Output 3:
[[1925    9   49   15    2]
 [  10 9527   39   41  383]
 [  21   92 7694  160   33]
 [  11   81  119 7765   24]
 [   1  314    9   24 7652]]

Accuracy for Output 1: 0.99752777

In [19]:
matrices = matrices3x3
mean = 0
std_dev = 50
num_iterations = 2000
filename = 'test_3x3.csv'
generate_csv(matrices, mean, std_dev, num_iterations, filename)

data = pd.read_csv("test_3x3.csv") 
model = load_model("C:\Ankit\Programs\RP\models\ed_9x9.keras")
test_models(data, model)

CSV file generated successfully.
Shapes of data:
X_test: (36000, 9)
y1_test: (36000,)
y2_test: (36000,)
y3_test: (36000,)
1125/1125 [==============================] - 2s 1ms/step - loss: 0.0907 - output1_loss: 5.7066e-04 - output2_loss: 0.0190 - output3_loss: 0.0147 - output1_accuracy: 0.9999 - output2_accuracy: 0.9968 - output3_accuracy: 0.9963
Test Results: [0.09065575897693634, 0.0005706642405129969, 0.01896851882338524, 0.014737711288034916, 0.999916672706604, 0.9967777729034424, 0.9962777495384216]
1125/1125 [==============================] - 2s 1ms/step

Confusion Matrix for Output 1:
[[ 3999     1]
 [    2 31998]]

Confusion Matrix for Output 2:
[[3990    1    4    5    0]
 [   1 7988    7    2    2]
 [   5    6 7985    4    0]
 [   5    0    6 7981    8]
 [   0   14    1   45 7940]]

Confusion Matrix for Output 3:
[[1994    1    5    0    0]
 [   0 9944    1    3   52]
 [   1    9 7973   17    0]
 [   1    7   11 7980    1]
 [   1   24    0    0 7975]]

Accuracy for Output 1: 0

In [18]:
matrices = matrices5x5
mean = 0
std_dev = 50
num_iterations = 2000
filename = 'test_5x5.csv'
generate_csv(matrices, mean, std_dev, num_iterations, filename)

data = pd.read_csv("test_5x5.csv") 
model = load_model("C:\Ankit\Programs\RP\models\ed_25x25.keras")
test_models(data, model)

CSV file generated successfully.
Shapes of data:
X_test: (36000, 25)
y1_test: (36000,)
y2_test: (36000,)
y3_test: (36000,)
1125/1125 [==============================] - 2s 1ms/step - loss: 0.0154 - output1_loss: 5.4669e-05 - output2_loss: 2.8662e-04 - output3_loss: 7.6315e-04 - output1_accuracy: 1.0000 - output2_accuracy: 1.0000 - output3_accuracy: 1.0000
Test Results: [0.015369231812655926, 5.466942093335092e-05, 0.00028661705437116325, 0.0007631455664522946, 1.0, 1.0, 0.9999722242355347]
1125/1125 [==============================] - 1s 1ms/step

Confusion Matrix for Output 1:
[[ 4000     0]
 [    0 32000]]

Confusion Matrix for Output 2:
[[4000    0    0    0    0]
 [   0 8000    0    0    0]
 [   0    0 8000    0    0]
 [   0    0    0 8000    0]
 [   0    0    0    0 8000]]

Confusion Matrix for Output 3:
[[2000    0    0    0    0]
 [   0 9999    0    1    0]
 [   0    0 8000    0    0]
 [   0    0    0 8000    0]
 [   0    0    0    0 8000]]

Accuracy for Output 1: 1.0
Accuracy for

In [17]:
matrices = matrices7x7
mean = 0
std_dev = 50
num_iterations = 2000
filename = 'test_7x7.csv'
generate_csv(matrices, mean, std_dev, num_iterations, filename)

data = pd.read_csv("test_7x7.csv") 
model = load_model("C:\Ankit\Programs\RP\models\ed_49x49.keras")
test_models(data, model)

CSV file generated successfully.
Shapes of data:
X_test: (36000, 49)
y1_test: (36000,)
y2_test: (36000,)
y3_test: (36000,)
1125/1125 [==============================] - 2s 1ms/step - loss: 0.0155 - output1_loss: 7.5756e-06 - output2_loss: 8.2123e-04 - output3_loss: 4.8054e-04 - output1_accuracy: 1.0000 - output2_accuracy: 1.0000 - output3_accuracy: 1.0000
Test Results: [0.01550114993005991, 7.575594736408675e-06, 0.0008212317479774356, 0.000480536138638854, 1.0, 1.0, 1.0]
1125/1125 [==============================] - 2s 2ms/step

Confusion Matrix for Output 1:
[[ 4000     0]
 [    0 32000]]

Confusion Matrix for Output 2:
[[4000    0    0    0    0]
 [   0 8000    0    0    0]
 [   0    0 8000    0    0]
 [   0    0    0 8000    0]
 [   0    0    0    0 8000]]

Confusion Matrix for Output 3:
[[ 2000     0     0     0     0]
 [    0 10000     0     0     0]
 [    0     0  8000     0     0]
 [    0     0     0  8000     0]
 [    0     0     0     0  8000]]

Accuracy for Output 1: 1.0
Accur

In [17]:
matrices = matrices7x7
mean = 0
std_dev = 20
num_iterations = 2000
filename = 'test_7x7.csv'
generate_csv(matrices, mean, std_dev, num_iterations, filename)

data = pd.read_csv("test_7x7.csv") 
model = load_model("C:\Ankit\Programs\RP\multi_output_model_49x49_smaller.keras")
test_models(data, model)

CSV file generated successfully.
Shapes of data:
X_test: (36000, 49)
y1_test: (36000,)
y2_test: (36000,)
y3_test: (36000,)
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - loss: 0.0072 - output1_accuracy: 1.0000 - output1_loss: 2.5545e-05 - output2_accuracy: 1.0000 - output2_loss: 1.2258e-04 - output3_accuracy: 1.0000 - output3_loss: 7.0486e-05
Test Results: [0.007145566400140524, 1.4167070730763953e-05, 7.793282566126436e-05, 6.079567174310796e-05, 1.0, 1.0, 1.0]
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step

Confusion Matrix for Output 1:
[[ 4000     0]
 [    0 32000]]

Confusion Matrix for Output 2:
[[4000    0    0    0    0]
 [   0 8000    0    0    0]
 [   0    0 8000    0    0]
 [   0    0    0 8000    0]
 [   0    0    0    0 8000]]

Confusion Matrix for Output 3:
[[ 2000     0     0     0     0]
 [    0 10000     0     0     0]
 [    0     0  8000     0     0]
 [    0     0     0  8000     0]
 [    0     0     0     0  8000]]

Accuracy for Output 1: 1.0
Accuracy for Output 2: 1.0
Acc

In [6]:
matrices = matrices5x5
mean = 0
std_dev = 20
num_iterations = 2000
filename = 'test_5x5.csv'
generate_csv(matrices, mean, std_dev, num_iterations, filename)

data = pd.read_csv("test_5x5.csv") 
model = load_model("C:\Ankit\Programs\RP\models\ed_25x25.keras")
test_models(data, model)

CSV file generated successfully.
Shapes of data:
X_test: (36000, 25)
y1_test: (36000,)
y2_test: (36000,)
y3_test: (36000,)
1125/1125 [==============================] - 2s 1ms/step - loss: 0.2148 - output1_loss: 0.0017 - output2_loss: 0.0720 - output3_loss: 0.1268 - output1_accuracy: 1.0000 - output2_accuracy: 0.9513 - output3_accuracy: 0.9447
Test Results: [0.21479476988315582, 0.0017264742637053132, 0.07200085371732712, 0.12680304050445557, 1.0, 0.9512777924537659, 0.9446666836738586]
1125/1125 [==============================] - 1s 1ms/step

Confusion Matrix for Output 1:
[[ 4000     0]
 [    0 32000]]

Confusion Matrix for Output 2:
[[2246    0 1739   15    0]
 [   0 8000    0    0    0]
 [   0    0 8000    0    0]
 [   0    0    0 8000    0]
 [   0    0    0    0 8000]]

Confusion Matrix for Output 3:
[[    8     0     0   756  1236]
 [    0 10000     0     0     0]
 [    0     0  8000     0     0]
 [    0     0     0  8000     0]
 [    0     0     0     0  8000]]

Accuracy for Outp