In [26]:
matrices3x3 = {
    'edge_00': [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]
    ],
    'edge_01': [
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]
    ],
    'edge_02': [
        [0, 255, 255],
        [255, 255, 255],
        [255, 255, 255]
    ],
    'edge_00': [
        [255, 0, 0],
        [0, 0, 0],
        [0, 0, 0]
    ],
    'edge_01': [
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 0]
    ],
    'edge_00': [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 255]
    ],
    'edge_11': [
        [0, 0, 0],
        [0, 0, 0],
        [255, 255, 255]
    ],
    'edge_12': [
        [255, 255, 255],
        [0, 0, 0],
        [0, 0, 0]
    ],
    'edge_13': [
        [255, 255, 255],
        [255, 255, 255],
        [0, 0, 0]
    ],
    'edge_14': [
        [0, 0, 0],
        [255, 255, 255],
        [255, 255, 255]
    ],
    'edge_21': [
        [255, 255, 0],
        [255, 0, 0],
        [0, 0, 0]
    ],
    'edge_22': [
        [0, 0, 255],
        [0, 255, 255],
        [255, 255, 255]
    ],
    'edge_23': [
        [0, 0, 0],
        [0, 0, 255],
        [0, 255, 255]
    ],
    'edge_24': [
        [255, 255, 255],
        [255, 255, 0],
        [255, 0, 0]
    ],
    'edge_31': [
        [255, 0, 0],
        [255, 0, 0],
        [255, 0, 0]
    ],
    'edge_32': [
        [0, 0, 255],
        [0, 0, 255],
        [0, 0, 255]
    ],
    'edge_33': [
        [0, 255, 255],
        [0, 255, 255],
        [0, 255, 255]
    ],
    'edge_34': [
        [255, 255, 0],
        [255, 255, 0],
        [255, 255, 0]
    ],
    'edge_41': [
        [255, 0,   0],
        [255, 255, 0],
        [255, 255, 255]
    ],
    'edge_42': [
        [0, 255, 255],
        [0, 0,   255],
        [0, 0,   0]
    ],
    'edge_43': [
        [255, 255, 255],
        [0, 255, 255],
        [0, 0, 255]
    ],
    'edge_44': [
        [0, 0, 0],
        [255, 0, 0],
        [255, 255, 0]
    ]
}
matrices5x5 = {
    'edge_00': [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],
    'edge_01': [
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]
    ],
    'edge_11': [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]
    ],
    'edge_12': [
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],
    'edge_13': [
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],
    'edge_14': [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]
    ],
    'edge_21': [
        [0, 0, 0, 0, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]
    ],
    'edge_22': [
        [255, 255, 255, 255, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],
    'edge_23': [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 255, 255, 255, 255]
    ],
    'edge_24': [
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 0, 0, 0, 0]
    ],
    'edge_31': [
        [0, 0, 0, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 255, 255]
    ],
    'edge_32': [
        [255, 255, 255, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 0, 0]
    ],
    'edge_33': [
        [0, 0, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 255, 255, 255]
    ],
    'edge_34': [
        [255, 255, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 0, 0, 0]
    ],
    'edge_41': [
        [255, 0, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 255, 0],
        [255, 255, 255, 255, 255]
    ],
    'edge_42': [
        [0, 255, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 0, 255],
        [0, 0, 0, 0, 0]
    ],
    'edge_43': [
        [0, 0, 0, 0, 0],
        [255, 0, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 255, 0]
    ],
    'edge_44': [
        [255, 255, 255, 255, 255],
        [0, 255, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 0, 255]
    ]
}

In [29]:
import cv2
import numpy as np
import csv

def generate_dataset(image_path, gt_path, N, matrices_N, output_csv):
    """
    Generate a CSV dataset from an image and its ground truth edge map.

    Parameters:
    - image_path (str): Path to the image .pgm file.
    - gt_path (str): Path to the ground truth edge map .pgm file.
    - N (int): Window size (3, 5, or 7).
    - matrices_N (dict): Dictionary of predefined edge patterns (e.g., 'edge_12').
    - output_csv (str): Path to the output CSV file.

    CSV Columns:
    - pixel_0 to pixel_(N^2-1): Normalized pixel values (0 to 1).
    - HasEdge: 0 or 1.
    - num1, num2: Edge type digits or -1 if unknown.
    """
    # Read the image and ground truth
    image = cv2.imread(image_path, cv2.IMREAD_UNCHANGED)
    gt = cv2.imread(gt_path, cv2.IMREAD_UNCHANGED)
    gt = cv2.bitwise_not(gt)

    # Validate inputs
    if image is None or gt is None:
        raise ValueError("Failed to read image or ground truth file.")
    if image.shape != gt.shape:
        raise ValueError("Image and ground truth must have the same shape.")
    assert N in [3, 5, 7], "Window size N must be 3, 5, or 7"

    # Ensure image is uint8 and contiguous
    if image.dtype != np.uint8:
        image = image.astype(np.uint8)
    image = np.ascontiguousarray(image)
    height, width = image.shape

    # Debug: Check raw image
    print(f"Raw image min: {image.min()}, max: {image.max()}")

    # Normalize to [0, 1]
    image_normalized = image.astype(float) / 255.0
    image_normalized = np.ascontiguousarray(image_normalized)
    print(f"Normalized image min: {image_normalized.min()}, max: {image_normalized.max()}")

    # Convert matrices to NumPy arrays
    matrices_N_np = {key: np.array(matrix) for key, matrix in matrices_N.items()}

    # Extract windows
    half_N = N // 2
    num_windows_y = height - 2 * half_N
    num_windows_x = width - 2 * half_N
    shape = (num_windows_y, num_windows_x, N, N)
    strides = image_normalized.strides + image_normalized.strides  # (row stride, col stride, row step, col step)

    try:
        img_windows = np.lib.stride_tricks.as_strided(
            image_normalized, shape=shape, strides=strides
        )
        gt_windows = np.lib.stride_tricks.as_strided(
            gt, shape=shape, strides=gt.strides + gt.strides
        )
    except ValueError as e:
        print(f"Stride extraction failed: {e}")
        raise

    # Flatten windows
    img_windows_flat = img_windows.reshape(-1, N * N)
    gt_windows_flat = gt_windows.reshape(-1, N * N)

    # Debug: Check window values
    print(f"Flattened windows min: {img_windows_flat.min()}, max: {img_windows_flat.max()}")
    print(f"Flattened windows min: {gt_windows_flat.min()}, max: {gt_windows_flat.max()}")

    # Validate and clip if necessary
    if img_windows_flat.min() < 0 or img_windows_flat.max() > 1:
        print("Warning: Invalid pixel values detected. Clipping to [0, 1].")
        img_windows_flat = np.clip(img_windows_flat, 0, 1)

    # Compute HasEdge
    HasEdge = (gt[half_N:-half_N, half_N:-half_N].ravel() == 255).astype(int)

    # Classify edge types (reshape gt_windows to 3D for comparison)
    gt_windows_3d = gt_windows_flat.reshape(-1, N, N)
    print(gt_windows_3d)
    edge_types = np.full(HasEdge.shape, 'unknown', dtype=object)
    for key, pattern in matrices_N_np.items():
        matches = np.all(gt_windows_3d == pattern, axis=(1, 2))
        edge_types[matches] = key

    # Extract num1 and num2
    def get_num1(et):
        if et == 'unknown':
            return 9
        parts = et.split('_')
        return int(parts[-1][0])

    def get_num2(et):
        if et == 'unknown':
            return 9
        parts = et.split('_')
        return int(parts[-1][1])

    get_num1_vec = np.vectorize(get_num1)
    get_num2_vec = np.vectorize(get_num2)
    num1 = get_num1_vec(edge_types)
    num2 = get_num2_vec(edge_types)

    # Combine data
    data = np.hstack((gt_windows_flat, HasEdge[:, None], num1[:, None], num2[:, None]))

    # Define header
    header = [f'pixel_{k}' for k in range(N * N)] + ['HasEdge', 'num1', 'num2']

    # Write to CSV
    with open(output_csv, 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(header)
        writer.writerows(data)

# Example usage

In [ ]:
generate_dataset('C:\Ankit\Programs\RP\images\\basket.pgm', 'C:\Ankit\Programs\RP\images\gt\\basket_gt_binary.pgm', 5, matrices5x5, 'C:\Ankit\Programs\RP\data\\train\\new_dataset_gt.csv')

Raw image min: 21, max: 241
Normalized image min: 0.08235294117647059, max: 0.9450980392156862
Flattened windows min: 0.08235294117647059, max: 0.9450980392156862
Flattened windows min: 0, max: 255
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 ...

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
