In [1]:
matrices3x3 = {
    'mat_3x3_00': [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]
    ],
    'mat_3x3_01': [
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]
    ],
    'mat_3x3_02': [
        [0, 255, 255],
        [255, 255, 255],
        [255, 255, 255]
    ],
    'mat_3x3_00': [
        [255, 0, 0],
        [0, 0, 0],
        [0, 0, 0]
    ],
    'mat_3x3_01': [
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 0]
    ],
    'mat_3x3_00': [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 255]
    ],
    'mat_3x3_11': [
        [0, 0, 0],
        [0, 0, 0],
        [255, 255, 255]
    ],
    'mat_3x3_12': [
        [255, 255, 255],
        [0, 0, 0],
        [0, 0, 0]
    ],
    'mat_3x3_13': [
        [255, 255, 255],
        [255, 255, 255],
        [0, 0, 0]
    ],
    'mat_3x3_14': [
        [0, 0, 0],
        [255, 255, 255],
        [255, 255, 255]
    ],
    'mat_3x3_21': [
        [255, 255, 0],
        [255, 0, 0],
        [0, 0, 0]
    ],
    'mat_3x3_22': [
        [0, 0, 255],
        [0, 255, 255],
        [255, 255, 255]
    ],
    'mat_3x3_23': [
        [0, 0, 0],
        [0, 0, 255],
        [0, 255, 255]
    ],
    'mat_3x3_24': [
        [255, 255, 255],
        [255, 255, 0],
        [255, 0, 0]
    ],
    'mat_3x3_31': [
        [255, 0, 0],
        [255, 0, 0],
        [255, 0, 0]
    ],
    'mat_3x3_32': [
        [0, 0, 255],
        [0, 0, 255],
        [0, 0, 255]
    ],
    'mat_3x3_33': [
        [0, 255, 255],
        [0, 255, 255],
        [0, 255, 255]
    ],
    'mat_3x3_34': [
        [255, 255, 0],
        [255, 255, 0],
        [255, 255, 0]
    ],
    'mat_3x3_41': [
        [255, 0,   0],
        [255, 255, 0],
        [255, 255, 255]
    ],
    'mat_3x3_42': [
        [0, 255, 255],
        [0, 0,   255],
        [0, 0,   0]
    ],
    'mat_3x3_43': [
        [255, 255, 255],
        [0, 255, 255],
        [0, 0, 255]
    ],
    'mat_3x3_44': [
        [0, 0, 0],
        [255, 0, 0],
        [255, 255, 0]
    ]
}

In [2]:
matrices5x5 = {
    'mat_5x5_00': [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],
    'mat_5x5_01': [
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]
    ],
    'mat_5x5_11': [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]
    ],
    'mat_5x5_12': [
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],
    'mat_5x5_13': [
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],
    'mat_5x5_14': [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]
    ],
    'mat_5x5_21': [
        [0, 0, 0, 0, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 255, 255, 255, 255],
        [255, 255, 255, 255, 255]
    ],
    'mat_5x5_22': [
        [255, 255, 255, 255, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ],
    'mat_5x5_23': [
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 255, 255, 255, 255]
    ],
    'mat_5x5_24': [
        [255, 255, 255, 255, 255],
        [255, 255, 255, 255, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 0, 0, 0, 0]
    ],
    'mat_5x5_31': [
        [0, 0, 0, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 255, 255]
    ],
    'mat_5x5_32': [
        [255, 255, 255, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 0, 0]
    ],
    'mat_5x5_33': [
        [0, 0, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 255, 255, 255]
    ],
    'mat_5x5_34': [
        [255, 255, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 0, 0, 0]
    ],
    'mat_5x5_41': [
        [255, 0, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 255, 0],
        [255, 255, 255, 255, 255]
    ],
    'mat_5x5_42': [
        [0, 255, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 0, 255],
        [0, 0, 0, 0, 0]
    ],
    'mat_5x5_43': [
        [0, 0, 0, 0, 0],
        [255, 0, 0, 0, 0],
        [255, 255, 0, 0, 0],
        [255, 255, 255, 0, 0],
        [255, 255, 255, 255, 0]
    ],
    'mat_5x5_44': [
        [255, 255, 255, 255, 255],
        [0, 255, 255, 255, 255],
        [0, 0, 255, 255, 255],
        [0, 0, 0, 255, 255],
        [0, 0, 0, 0, 255]
    ]
}

In [3]:
matrices7x7 = {
    'mat_7x7_00': [
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]
    ],
    'mat_7x7_01': [
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255]
    ],
    'mat_7x7_11': [
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255]
    ],
    'mat_7x7_12': [
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]
    ],
    'mat_7x7_13': [
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]
    ],
    'mat_7x7_14': [
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255]
    ],
    'mat_7x7_21': [
        [0, 0, 0, 0, 0, 0, 255],
        [0, 0, 0, 0, 0, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 255, 255, 255, 255, 255],
        [0, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 255]
    ],
    'mat_7x7_22': [
        [255, 255, 255, 255, 255, 255, 0],
        [255, 255, 255, 255, 255, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 0, 0, 0, 0, 0],
        [255, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]
    ],
    'mat_7x7_23': [
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 255],
        [0, 0, 0, 0, 0, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 255, 255, 255, 255, 255],
        [0, 255, 255, 255, 255, 255, 255]
    ],
    'mat_7x7_24': [
        [255, 255, 255, 255, 255, 255, 255],
        [255, 255, 255, 255, 255, 255, 0],
        [255, 255, 255, 255, 255, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 0, 0, 0, 0, 0],
        [255, 0, 0, 0, 0, 0, 0]
    ],
    'mat_7x7_31': [
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255]
    ],
    'mat_7x7_32': [
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0]
    ],
    'mat_7x7_33': [
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255]
    ],
    'mat_7x7_34': [
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0]
    ],
    'mat_7x7_41': [
        [255, 0, 0, 0, 0, 0, 0],
        [255, 255, 0, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 255, 0, 0],
        [255, 255, 255, 255, 255, 255, 0],
        [255, 255, 255, 255, 255, 255, 255]
    ],

    'mat_7x7_42': [
        [0, 255, 255, 255, 255, 255, 255],
        [0, 0, 255, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 0, 255, 255],
        [0, 0, 0, 0, 0, 0, 255],
        [0, 0, 0, 0, 0, 0, 0]
    ],

    'mat_7x7_43': [
        [0, 0, 0, 0, 0, 0, 0],
        [255, 0, 0, 0, 0, 0, 0],
        [255, 255, 0, 0, 0, 0, 0],
        [255, 255, 255, 0, 0, 0, 0],
        [255, 255, 255, 255, 0, 0, 0],
        [255, 255, 255, 255, 255, 0, 0],
        [255, 255, 255, 255, 255, 255, 0]
    ],

    'mat_7x7_44': [
        [255, 255, 255, 255, 255, 255, 255],
        [0, 255, 255, 255, 255, 255, 255],
        [0, 0, 255, 255, 255, 255, 255],
        [0, 0, 0, 255, 255, 255, 255],
        [0, 0, 0, 0, 255, 255, 255],
        [0, 0, 0, 0, 0, 255, 255],
        [0, 0, 0, 0, 0, 0, 255]
    ]
}


In [8]:
import numpy as np
import pandas as pd

# Function to add random noise to a matrix
def add_noise(matrix, mean=0, std_dev=30):
    gaussian_noise = np.random.normal(mean, std_dev, matrix.shape)
    noisy_matrix = matrix + gaussian_noise
    noisy_matrix = np.clip(noisy_matrix, 0, 255)  # Ensure values are within [0, 255]
    return noisy_matrix

#function to generate csv file for the matrices
def generate_csv(matrices, mean, std_dev_start, std_dev_end, step, num_iterations, filename):
    data = []

    for matrix_name, matrix in matrices.items():
        base_matrix = np.array(matrix)
        first_digit = int(matrix_name[-2])
        second_digit = int(matrix_name[-1])
        size = len(matrix[0])
        for std_dev in range(std_dev_start, std_dev_end, step):
            for _ in range(num_iterations):
                # Add random noise
                noisy_matrix = add_noise(base_matrix, mean, std_dev)
                #normalise the matrix
                noisy_matrix = noisy_matrix/255.0
                # Flatten the matrix to store as a row
                noisy_matrix_flat = noisy_matrix.flatten()
        
                if first_digit == 0:
                    edge_detected = 0
                else:
                    edge_detected = 1
                
                # Append the flattened matrix and labels to the data list
                data.append(list(noisy_matrix_flat) + [edge_detected, first_digit, second_digit])
    
    # Convert the data to a DataFrame and save to CSV
    columns = [f'pixel_{i}' for i in range(size*size)] + ['edge_detected', 'first_digit', 'second_digit']
    df = pd.DataFrame(data, columns=columns)

    df.to_csv(filename, index=False)

    print("CSV file generated successfully.")

In [9]:
matrices = matrices3x3
mean = 0
std_dev_start = 20
std_dev_end = 61
step = 10
num_iterations = 2000
filename = 'C:\Ankit\Programs\RP\data\\train\mat_3x3.csv'
generate_csv(matrices, mean, std_dev_start, std_dev_end, step, num_iterations, filename)

CSV file generated successfully.


In [10]:
matrices = matrices5x5
mean = 0
std_dev_start = 20
std_dev_end = 61
step = 10
num_iterations = 2000
filename = 'C:\Ankit\Programs\RP\data\\train\mat_5x5.csv'
generate_csv(matrices, mean, std_dev_start, std_dev_end, step, num_iterations, filename)

CSV file generated successfully.


In [11]:
matrices = matrices7x7
mean = 0
std_dev_start = 20
std_dev_end = 61
step = 10
num_iterations = 2000
filename = 'C:\Ankit\Programs\RP\data\\train\mat_7x7.csv'
generate_csv(matrices, mean, std_dev_start, std_dev_end, step, num_iterations, filename)

CSV file generated successfully.


## Training the nn

In [12]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Input, Conv1D, Dropout, Flatten, Dense
from tensorflow.keras.regularizers import l2
from tensorflow.keras.callbacks import EarlyStopping

def load_data(file_path):
    # Load data from file
    data = np.loadtxt(file_path, delimiter=',', skiprows=1)
    
    # Extract features
    X = data[:, :-3]  # All columns except the last three are features
    
    # Extract targets
    y1 = data[:, -3]  # First output (binary: Yes/No)
    y2 = data[:, -2]  # Second output (integer: 1–4)
    y3 = data[:, -1]  # Third output (integer: 1–4)
    
    # Split into train and test sets
    X_train, X_test, y_train1, y_test1, y_train2, y_test2, y_train3, y_test3 = train_test_split(
        X, y1, y2, y3, test_size=0.3, random_state=42
    )
    
    # Combine outputs into dictionaries for easier handling
    y_train = {'output1': y_train1, 'output2': y_train2, 'output3': y_train3}
    y_test = {'output1': y_test1, 'output2': y_test2, 'output3': y_test3}
    
    return X_train, X_test, y_train, y_test


def build_multi_output_model(input_size):
    # Shared base
    inputs = Input(shape=(input_size, 1))
    x = Conv1D(8, kernel_size=3, activation='relu', padding='same', kernel_regularizer=l2(0.001))(inputs)
    x = Dropout(0.2)(x)
    x = Flatten()(x)
    
    # Branch 1: Binary classification (Yes/No)
    branch1 = Dense(4, activation='relu', kernel_regularizer=l2(0.001))(x)
    # branch1 = Dropout(0.2)(branch1)
    output1 = Dense(1, activation='sigmoid', name='output1')(branch1)  # Sigmoid for binary output
    
    # Branch 2: Multiclass classification (1–4)
    branch2 = Dense(4, activation='relu', kernel_regularizer=l2(0.001))(x)
    # branch2 = Dropout(0.2)(branch2)
    output2 = Dense(5, activation='softmax', name='output2')(branch2)  # Softmax for 4-class output
    
    # Branch 3: Multiclass classification (1–4)
    branch3 = Dense(4, activation='relu', kernel_regularizer=l2(0.001))(x)
    # branch3 = Dropout(0.2)(branch3)
    output3 = Dense(5, activation='softmax', name='output3')(branch3)  # Softmax for 4-class output
    
    # Combine into a multi-output model
    model = Model(inputs=inputs, outputs=[output1, output2, output3])
    return model

def train_and_evaluate_multi_output_model(X_train, X_test, y_train, y_test, input_size):
    # Reshape X data for Conv1D input
    X_train = X_train.reshape(-1, input_size, 1)
    X_test = X_test.reshape(-1, input_size, 1)

    # Directly extract outputs from dictionaries
    y1_train, y2_train, y3_train = y_train['output1'], y_train['output2'], y_train['output3']
    y1_test, y2_test, y3_test = y_test['output1'], y_test['output2'], y_test['output3']

    # Build the model
    model = build_multi_output_model(input_size)
    model.compile(
        optimizer='adam',
        loss={
            'output1': 'binary_crossentropy',
            'output2': 'sparse_categorical_crossentropy',
            'output3': 'sparse_categorical_crossentropy'
        },
        metrics={
            'output1': ['accuracy'],
            'output2': ['accuracy'],
            'output3': ['accuracy']
        }
    )

    # Early stopping callback
    early_stopping = EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

    # Train the model
    history = model.fit(
        X_train,
        {'output1': y1_train, 'output2': y2_train, 'output3': y3_train},
        epochs=50,
        batch_size=128,
        validation_split=0.3,
        callbacks=[early_stopping]
    )

    # Save the model
    model_name = f"ed_{input_size}x{input_size}.keras"
    model.save(model_name)
    print(f"Model saved as {model_name}")

    # Evaluate the model
    results = model.evaluate(X_test, {'output1': y1_test, 'output2': y2_test, 'output3': y3_test})
    print("Test Results:", results)

    # Generate predictions
    preds = model.predict(X_test)
    y1_pred = (preds[0] > 0.5).astype(int)  # Binary predictions for output1
    y2_pred = np.argmax(preds[1], axis=1)  # Multiclass predictions for output2
    y3_pred = np.argmax(preds[2], axis=1)  # Multiclass predictions for output3

    # Confusion matrices
    print("Confusion Matrix for Output 1:")
    print(confusion_matrix(y1_test, y1_pred))
    print("Confusion Matrix for Output 2:")
    print(confusion_matrix(y2_test, y2_pred))
    print("Confusion Matrix for Output 3:")
    print(confusion_matrix(y3_test, y3_pred))

    # Accuracy scores
    print("Accuracy for Output 1:", accuracy_score(y1_test, y1_pred))
    print("Accuracy for Output 2:", accuracy_score(y2_test, y2_pred))
    print("Accuracy for Output 3:", accuracy_score(y3_test, y3_pred))


In [13]:
X_train, X_test, y_train, y_test = load_data('C:\Ankit\Programs\RP\data\\train\mat_3x3.csv')
train_and_evaluate_multi_output_model(X_train, X_test, y_train, y_test, input_size=9)

Epoch 1/50
690/690 [==============================] - 4s 3ms/step - loss: 2.1980 - output1_loss: 0.2671 - output2_loss: 1.0978 - output3_loss: 0.7856 - output1_accuracy: 0.8910 - output2_accuracy: 0.5212 - output3_accuracy: 0.7002 - val_loss: 1.0214 - val_output1_loss: 0.1281 - val_output2_loss: 0.6574 - val_output3_loss: 0.1574 - val_output1_accuracy: 0.9280 - val_output2_accuracy: 0.7046 - val_output3_accuracy: 0.9535
Epoch 2/50
690/690 [==============================] - 2s 3ms/step - loss: 0.9564 - output1_loss: 0.0937 - output2_loss: 0.6153 - output3_loss: 0.1558 - output1_accuracy: 0.9703 - output2_accuracy: 0.7191 - output3_accuracy: 0.9534 - val_loss: 0.7042 - val_output1_loss: 0.0575 - val_output2_loss: 0.4959 - val_output3_loss: 0.0519 - val_output1_accuracy: 0.9949 - val_output2_accuracy: 0.7748 - val_output3_accuracy: 0.9889
Epoch 3/50
690/690 [==============================] - 2s 3ms/step - loss: 0.7607 - output1_loss: 0.0545 - output2_loss: 0.5103 - output3_loss: 0.0949 - 

In [14]:
#5x5
X_train, X_test, y_train, y_test = load_data('C:\Ankit\Programs\RP\data\\train\mat_5x5.csv')
train_and_evaluate_multi_output_model(X_train, X_test, y_train, y_test, input_size=25)

Epoch 1/50
690/690 [==============================] - 5s 5ms/step - loss: 1.4816 - output1_loss: 0.1679 - output2_loss: 0.6305 - output3_loss: 0.6158 - output1_accuracy: 0.9369 - output2_accuracy: 0.7750 - output3_accuracy: 0.7715 - val_loss: 0.3359 - val_output1_loss: 0.0644 - val_output2_loss: 0.0543 - val_output3_loss: 0.1103 - val_output1_accuracy: 0.9990 - val_output2_accuracy: 0.9996 - val_output3_accuracy: 0.9911
Epoch 2/50
690/690 [==============================] - 2s 3ms/step - loss: 0.2431 - output1_loss: 0.0515 - output2_loss: 0.0386 - output3_loss: 0.0466 - output1_accuracy: 0.9983 - output2_accuracy: 0.9974 - output3_accuracy: 0.9929 - val_loss: 0.1594 - val_output1_loss: 0.0398 - val_output2_loss: 0.0113 - val_output3_loss: 0.0095 - val_output1_accuracy: 0.9999 - val_output2_accuracy: 0.9998 - val_output3_accuracy: 0.9994
Epoch 3/50
690/690 [==============================] - 2s 3ms/step - loss: 0.1595 - output1_loss: 0.0331 - output2_loss: 0.0177 - output3_loss: 0.0200 - 

In [15]:
X_train, X_test, y_train, y_test = load_data('C:\Ankit\Programs\RP\data\\train\mat_7x7.csv')
train_and_evaluate_multi_output_model(X_train, X_test, y_train, y_test, input_size=49)

Epoch 1/50
690/690 [==============================] - 5s 4ms/step - loss: 1.3376 - output1_loss: 0.1322 - output2_loss: 0.7417 - output3_loss: 0.3996 - output1_accuracy: 0.9520 - output2_accuracy: 0.6995 - output3_accuracy: 0.8623 - val_loss: 0.5458 - val_output1_loss: 0.0086 - val_output2_loss: 0.3885 - val_output3_loss: 0.0636 - val_output1_accuracy: 1.0000 - val_output2_accuracy: 0.8325 - val_output3_accuracy: 0.9952
Epoch 2/50
690/690 [==============================] - 3s 4ms/step - loss: 0.4468 - output1_loss: 0.0039 - output2_loss: 0.3357 - output3_loss: 0.0298 - output1_accuracy: 1.0000 - output2_accuracy: 0.8425 - output3_accuracy: 0.9976 - val_loss: 0.3142 - val_output1_loss: 0.0019 - val_output2_loss: 0.2352 - val_output3_loss: 0.0048 - val_output1_accuracy: 1.0000 - val_output2_accuracy: 0.8894 - val_output3_accuracy: 0.9999
Epoch 3/50
690/690 [==============================] - 3s 4ms/step - loss: 0.2891 - output1_loss: 0.0019 - output2_loss: 0.2115 - output3_loss: 0.0119 - 

# Model Evaluation Summary

The model architecture is evaluated under three configurations: **3x3**, **5x5**, and **7x7** input settings. Each configuration employs shared feature extraction layers and task-specific dense layers. The performance is measured for three outputs: Binary Classification (Output 1), Multiclass Classification with 4 classes (Output 2), and another Multiclass Classification with 4 classes (Output 3).

---

## **Model Configurations**

### **3x3 Model**
- **Inputs**: 9
- **Hidden Units**: 9
- **Dropout**: 0.3
- **Epochs**: 50
- **Learning Rate**: 0.001

### **5x5 Model**
- **Inputs**: 25
- **Hidden Units**: 25
- **Dropout**: 0.3
- **Epochs**: 50
- **Learning Rate**: 0.001

### **7x7 Model**
- **Inputs**: 49
- **Hidden Units**: 48
- **Dropout**: 0.3
- **Epochs**: 50
- **Learning Rate**: 0.001

---

## **Results**

### **3x3 Model**

- **Confusion Matrices**:

  - **Output 1 (Binary Classification)**:
    ```
    [[ 4219     0]
     [    0 33581]]
    ```

  - **Output 2 (Multiclass Classification with 4 classes)**:
    ```
    [[4219    0    0    0    0]
     [   0 8447    0    0    1]
     [   0    0 8333    2    0]
     [   0    0    0 8399    0]
     [   0    1    0    5 8393]]
    ```

  - **Output 3 (Multiclass Classification with 4 classes)**:
    ```
    [[ 2118     0     2     0     0]
     [    0 10553     0     1     5]
     [    0     1  8273     4     0]
     [    0     0     4  8376     1]
     [    0     1     0     0  8461]]
    ```

- **Accuracy**:
  - **Output 1**: **1.0**
  - **Output 2**: **0.999761**
  - **Output 3**: **0.999497**

---

### **5x5 Model**

- **Confusion Matrices**:

  - **Output 1 (Binary Classification)**:
    ```
    [[ 4219     0]
     [    0 33581]]
    ```

  - **Output 2 (Multiclass Classification with 4 classes)**:
    ```
    [[4219    0    0    0    0]
     [   0 8448    0    0    0]
     [   0    0 8335    0    0]
     [   0    0    0 8399    0]
     [   0    0    0    0 8399]]
    ```

  - **Output 3 (Multiclass Classification with 4 classes)**:
    ```
    [[ 2120     0     0     0     0]
     [    0 10559     0     0     0]
     [    0     0  8278     0     0]
     [    0     0     0  8381     0]
     [    0     0     0     0  8462]]
    ```

- **Accuracy**:
  - **Output 1**: **1.0**
  - **Output 2**: **1.0**
  - **Output 3**: **1.0**

---

### **7x7 Model**

- **Confusion Matrices**:

  - **Output 1 (Binary Classification)**:
    ```
    [[ 4219     0]
     [    0 33581]]
    ```

  - **Output 2 (Multiclass Classification with 4 classes)**:
    ```
    [[4219    0    0    0    0]
     [   0 8448    0    0    0]
     [   0    0 8335    0    0]
     [   0    0    0 8399    0]
     [   0    0    0    0 8399]]
    ```

  - **Output 3 (Multiclass Classification with 4 classes)**:
    ```
    [[ 2120     0     0     0     0]
     [    0 10559     0     0     0]
     [    0     0  8278     0     0]
     [    0     0     0  8381     0]
     [    0     0     0     0  8462]]
    ```

- **Accuracy**:
  - **Output 1**: **1.0**
  - **Output 2**: **1.0**
  - **Output 3**: **1.0**


In [16]:
import tensorflow as tf
model_3x3 = tf.keras.models.load_model("C:\Ankit\Programs\RP\models\ed_9x9.keras")
model_5x5 = tf.keras.models.load_model("C:\Ankit\Programs\RP\models\ed_25x25.keras") 
model_7x7 = tf.keras.models.load_model("C:\Ankit\Programs\RP\models\ed_49x49.keras")
print("Model for 3x3 matrices")
model_3x3.summary()
print("\n")
print("Model for 5x5 matrices")
model_5x5.summary()
print("\n")
print("Model for 7x7 matrices")
model_7x7.summary()

Model for 3x3 matrices
Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_1 (InputLayer)        [(None, 9, 1)]               0         []                            
                                                                                                  
 conv1d (Conv1D)             (None, 9, 8)                 32        ['input_1[0][0]']             
                                                                                                  
 dropout (Dropout)           (None, 9, 8)                 0         ['conv1d[0][0]']              
                                                                                                  
 flatten (Flatten)           (None, 72)                   0         ['dropout[0][0]']             
                                                                       

## Testing with custom inputs

In [18]:
import numpy as np
import pandas as pd

# Function to add random noise to a matrix
def add_noise(matrix, noise_level=30):
    noisy_matrix = matrix + np.random.randint(-noise_level, noise_level + 1, matrix.shape)
    noisy_matrix = np.clip(noisy_matrix, 0, 255)
    return noisy_matrix

#function to generate csv file for the matrices
def generate_csv(matrices, noise_level, num_iterations, filename):
    data = []
    
    for matrix_name, matrix in matrices.items():
        base_matrix = np.array(matrix)
        first_digit = int(matrix_name[-2])
        second_digit = int(matrix_name[-1])
        size = len(matrix[0])
        
        for _ in range(num_iterations):
            # Add random noise
            noisy_matrix = add_noise(base_matrix, noise_level)
            # Normalise the matrix to
            noisy_matrix = noisy_matrix / 255.0
            
            # Flatten the matrix to store as a row
            noisy_matrix_flat = noisy_matrix.flatten()
    
            if first_digit == 0:
                edge_detected = 0
            else:
                edge_detected = 1
            
            # Append the flattened matrix and labels to the data list
            data.append(list(noisy_matrix_flat))
    
    # Convert the data to a DataFrame and save to CSV
    columns = [f'pixel_{i}' for i in range(size*size)]
    df = pd.DataFrame(data, columns=columns)
    
    df.to_csv(filename, index=False)
    
    print("Custom CSV file generated successfully.")

In [19]:
##Automatic testing from csv file

import numpy as np
import pandas as pd
from tensorflow.keras.models import load_model

# Function to load custom input from CSV, make predictions, and print results
def load_and_predict_from_csv(model_path, csv_path):
    # Load the model
    model = load_model(model_path)
    print(f"Model loaded from {model_path}")
    
    # Load custom input from CSV
    custom_input = pd.read_csv(csv_path, header=0).values  # Read CSV as NumPy array
    print(f"Loaded input from {csv_path}:\n{custom_input}")
    for csi in custom_input:
    # Preprocess the input (flatten and reshape for Conv1D model)
        csi = csi.flatten()  # Flatten the matrix into a 1D array
        csi = csi.reshape(1, -1, 1)  # Reshape to (1, input_size, 1)
    
        # Make predictions
        predictions = model.predict(csi)
        
        # Interpret predictions
        has_edge = "Yes" if predictions[0][0] > 0.5 else "No"  # Binary output (threshold at 0.5)
        edge_no1 = np.argmax(predictions[1], axis=1)[0]     
        edge_no2 = np.argmax(predictions[2], axis=1)[0]     
        
        # Print output in desired format
        print(f"Has Edge: {has_edge}")
        print(f"Edge no: {edge_no1}, {edge_no2}")

In [40]:
#3x3 test manual
matrices = matrices3x3
noise_level = 100
num_iterations = 1
filename = 'custom_3x3_inputs.csv'
generate_csv(matrices, noise_level, num_iterations, filename)

csv_path = 'custom_3x3_inputs.csv'
model_path = 'C:\Ankit\Programs\RP\models\ed_9x9.keras'
load_and_predict_from_csv(model_path, csv_path)

Custom CSV file generated successfully.
Model loaded from C:\Ankit\Programs\RP\multi_output_model_9x9_smaller.keras
Loaded input from custom_3x3_inputs.csv:
[[0.         0.16470588 0.07058824 0.         0.31764706 0.12941176
  0.01960784 0.12156863 0.20392157]
 [1.         1.         0.83529412 1.         1.         1.
  0.79607843 1.         1.        ]
 [0.         0.         0.         0.         0.06666667 0.04313725
  0.80784314 1.         1.        ]
 [1.         0.84705882 1.         0.05882353 0.25882353 0.
  0.         0.36862745 0.        ]
 [0.83921569 0.7372549  1.         0.85098039 1.         1.
  0.28235294 0.         0.        ]
 [0.         0.22745098 0.         0.74509804 0.99215686 0.92941176
  1.         1.         0.7372549 ]
 [1.         0.90196078 0.         1.         0.17647059 0.
  0.05882353 0.15294118 0.        ]
 [0.         0.         0.69019608 0.         0.97647059 1.
  1.         1.         0.80784314]
 [0.25098039 0.15686275 0.         0.         0.   

In [25]:
#5x5 test manual
matrices = matrices5x5
noise_level = 100
num_iterations = 1
filename = 'custom_5x5_inputs.csv'
generate_csv(matrices, noise_level, num_iterations, filename)

csv_path = 'custom_5x5_inputs.csv'
model_path = 'C:\Ankit\Programs\RP\models\ed_25x25.keras'
load_and_predict_from_csv(model_path, csv_path)

Custom CSV file generated successfully.
Model loaded from C:\Ankit\Programs\RP\multi_output_model_25x25_smaller.keras
Loaded input from custom_5x5_inputs.csv:
[[0.         0.03137255 0.         0.29803922 0.         0.23921569
  0.2745098  0.23137255 0.21176471 0.         0.31372549 0.23921569
  0.         0.30196078 0.         0.         0.21176471 0.34901961
  0.23921569 0.2745098  0.         0.14901961 0.30588235 0.39215686
  0.25490196]
 [0.72156863 1.         0.63921569 1.         0.75686275 1.
  0.89803922 1.         0.85490196 1.         0.70980392 1.
  0.89411765 0.61568627 0.96470588 0.80784314 1.         0.65098039
  0.89411765 0.91372549 0.9372549  1.         0.63921569 0.95294118
  1.        ]
 [0.         0.06666667 0.         0.         0.27843137 0.
  0.03921569 0.         0.         0.         0.         0.21176471
  0.         0.3372549  0.02745098 1.         1.         0.83137255
  0.96078431 0.84705882 1.         1.         0.65882353 1.
  1.        ]
 [1.         1.

In [26]:
#7x7 test manual
matrices = matrices7x7
noise_level = 100
num_iterations = 1
filename = 'custom_7x7_inputs.csv'
generate_csv(matrices, noise_level, num_iterations, filename)

csv_path = 'custom_7x7_inputs.csv'
model_path = 'C:\Ankit\Programs\RP\models\ed_49x49.keras'
load_and_predict_from_csv(model_path, csv_path)

Custom CSV file generated successfully.
Model loaded from C:\Ankit\Programs\RP\multi_output_model_49x49_smaller.keras
Loaded input from custom_7x7_inputs.csv:
[[0.31764706 0.18431373 0.22745098 0.17647059 0.05098039 0.0627451
  0.18823529 0.         0.28235294 0.         0.         0.
  0.36470588 0.01568627 0.         0.29411765 0.10196078 0.
  0.         0.2627451  0.         0.07058824 0.22745098 0.21568627
  0.09411765 0.         0.         0.         0.10980392 0.01568627
  0.23921569 0.26666667 0.         0.         0.19607843 0.10980392
  0.         0.34509804 0.16078431 0.30980392 0.         0.
  0.         0.         0.         0.         0.12156863 0.18431373
  0.3254902 ]
 [1.         1.         1.         1.         0.77254902 1.
  0.73333333 0.99607843 1.         1.         1.         1.
  0.82745098 0.84705882 1.         1.         0.89019608 0.79607843
  0.83921569 0.77647059 1.         1.         1.         0.82352941
  0.9372549  0.98823529 1.         0.96862745 0.9686